### ISSUE TITLE
Observations on Nokia 8.1 debloating

### ISSUE THREAD

**Issue by abhikr713** [thanuj10/Nokia-Debloater#10]
Hi,
First of all thanks for creating this script.

- At the end it gave me a error saying unable to clean dalvik cache
- I can still see many evenwell apps in the apps list

com.evenwell.whitebalance.overlay.base
com.evenwell.settings.data.overlay.d.base.s600ww
com.evenwell.factorywizard
com.evenwell.foxlauncher.partner
com.evenwell.legalterm.overlay.base
com.evenwell.fqc
com.evenwell.settings.data.overlay.base
com.evenwell.phone.overlay.base
com.evenwell.legalterm
com.evenwell.fmradio.overlay.d.base.s600ww
com.evenwell.factorywizard.overlay.base
com.evenwell.SetupWizard
com.evenwell.bokeheditor
com.evenwell.SetupWizard.overlay.base
com.evenwell.bokeheditor.overlay.base
com.evenwell.SetupWizard.overlay.d.base.s600ww
com.evenwell.fmradio
com.evenwell.whitebalance
com.evenwell.fmradio.overlay.base 

Just wanted to know if they can be removed, if so could you please add them to your script?

**Comment by mll0** [comment]
In the same spirit, on my 5.1 Plus that is with the march 2020 updates, these new flavours can be added:
`adb.exe shell pm uninstall --user 0 com.evenwell.batteryprotect.overlay.d.base.s600e0
adb.exe shell pm uninstall --user 0 com.evenwell.powersaving.g3.overlay.d.base.s600e0
adb.exe shell pm uninstall --user 0 com.evenwell.powersaving.g3.overlay.base`

**Comment by mll0** [comment]
> com.evenwell.bokeheditor
> com.evenwell.fmradio
> com.evenwell.whitebalance

I see some stuff that's potentially dangerous to remove. They might interfere with the camera app functionality, and remove the FM radio app.

**Comment by thanuj10** [comment]
These are some new apps that aren't present on my phone. Will look more into it.

> com.evenwell.bokeheditor

This app is necessary for you to edit the level of Bokeh or as its commnly known - Background blur when you click pictures in Portrait mode.

Regarding the other apps, I've left them from debloating voluntarily as they are either essential or I can't find what they seem to do. I will some of the apps you mentioned though :) 

Edit - Added these apps back. Available on the latest release.
