### ISSUE TITLE
After running, some evenwell still exist

### ISSUE THREAD

**Issue by rapdodge** [thanuj10/Nokia-Debloater#12]
After running the debloater, i check some evenwell still exist, i think some useful...
![image](https://user-images.githubusercontent.com/33513626/88898298-b6055c80-d276-11ea-8880-db045ff1ea54.png)

Some "powersaving" still exist...  Can take look into this? Sometimes WhatsApp notifications not show up
com.evenwell.powersaving.g3.overlay.d.base.s600id
com.evenwell.powersaving.g3.overlay.base

**Comment by thanuj10** [comment]
Notifications not arriving on time is android-system wide problem affecting many phones across different OEs. Can't really do anything from my end. Also, If you could provide the list of some powersave apps, I can add it to my list :)

**Comment by rapdodge** [comment]
> 
> 
> Notifications not arriving on time is android-system wide problem affecting many phones across different OEs. Can't really do anything from my end. Also, If you could provide the list of some powersave apps, I can add it to my list :)

Can you add this?
com.evenwell.powersaving.g3.overlay.d.base.s600id
com.evenwell.powersaving.g3.overlay.base
com.evenwell.batteryprotect.overlay.d.base.s600id
com.evenwell.nps.overlay.d.base.s600id

**Comment by thanuj10** [comment]
> > Notifications not arriving on time is android-system wide problem affecting many phones across different OEs. Can't really do anything from my end. Also, If you could provide the list of some powersave apps, I can add it to my list :)
> 
> Can you add this?
> com.evenwell.powersaving.g3.overlay.d.base.s600id
> com.evenwell.powersaving.g3.overlay.base
> com.evenwell.batteryprotect.overlay.d.base.s600id
> com.evenwell.nps.overlay.d.base.s600id

These apps will be added by in tomorrow's update.

**Comment by rapdodge** [comment]
> 
> 
> > > Notifications not arriving on time is android-system wide problem affecting many phones across different OEs. Can't really do anything from my end. Also, If you could provide the list of some powersave apps, I can add it to my list :)
> > 
> > 
> > Can you add this?
> > com.evenwell.powersaving.g3.overlay.d.base.s600id
> > com.evenwell.powersaving.g3.overlay.base
> > com.evenwell.batteryprotect.overlay.d.base.s600id
> > com.evenwell.nps.overlay.d.base.s600id
> 
> These apps will be added by in tomorrow's update.

Thanks, really appreciate it.

**Comment by thanuj10** [comment]
Added these apps in the latest release. Closing the issue.
