### ISSUE TITLE
Ask user which apps to debloat

### ISSUE THREAD

**Issue by Sid127** [thanuj10/Nokia-Debloater#2]
Can do `pm list packages evenwell` to get all Evenwell apps and ask user which ones to disable and save it in a file or provide predefined list. Use that file to reinstall if needed. 

Can similarly debloat Google Apps

**Comment by thanuj10** [comment]
This could be tough to configure, But he let's see what we can do.

**Comment by Sid127** [comment]
The way I've configured it on the Linux version is by providing the script a configuration file in it's working directory, and the script itself reads the file line by line and performs the uninstall using a while-do-done loop.

**Comment by thanuj10** [comment]
Oh okay. Lemme see what I can do then.

**Comment by nebulakl** [comment]
Here is a oneliner I used on my Nokia 1 Plus to remove all packages that contain `evenwell` in their names. It is supposed to be used in a `adb` shell.

```bash
for P in `pm list package | sort | grep evenwell | sed -e 's/package://g'`; do pm uninstall --user 0 $P; done
```

I think we can achieve what @Sid127 is looking for if we slightly modify the `do` block.

**Comment by Sid127** [comment]
we don't want to remove all evenwell packages, because removing some of them breaks the system. What we want to be able to do is give power-users an option to choose which unnecessary packages they want to remove.
