### ISSUE TITLE
Option 2 will not work and Typos

### ISSUE THREAD

**Issue by TTothh** [thanuj10/Nokia-Debloater#6]
![image](https://user-images.githubusercontent.com/37255556/74089899-35735980-4aa6-11ea-8ae5-66587abf22c5.png)

Typo on line 13: disble instead of Disable

Typo on line 19: %choicr% should be %choice%

**Comment by thanuj10** [comment]
Thanks for pointing out, The latest release was a rushed one. I'll push a hotfix.

Edit - There is a fix now, Can you try running the script again?
