### ISSUE TITLE
debloating end-of-2019 devices

### ISSUE THREAD

**Issue by omicron-b** [thanuj10/Nokia-Debloater#8]
Hello!

Nokia 6.2 and 7.2 (maybe others too) come with some preinstalled telemetry, including 3rd party
[source 1 (German)](https://www.androidpit.de/forum/801980/kennt-jemand-das-paket-co-sitic-pp) [source 2](https://www.reddit.com/r/privacy/comments/fbxg0a/less_than_a_year_after_removing_3rd_party/)

Would it be out of scope of your script to add support for such devices or no?
I do not have a Windows PC so I can not really test a script and make a PR, so I am just letting you know of these possible issues.
My very simple Linux script looks like this:
https://github.com/omicron-b/nokia-debloater/blob/master/debloat-series2.sh#L3-L9

forgot to mention: Nokia 6.2 does not have evenwell apps preinstalled, probably others do not, too

**Comment by thanuj10** [comment]
No no. Thanks for letting me know 😀

I'll add the apps to my list, I just need some help. Can you list all the packages that you think is telemetry on the end-of-2019 devices via adb and send me a screenshot or list?

**Comment by omicron-b** [comment]
Ok, here are the packages I removed from my device (6.2) 3 days ago to stop telemetry, and everything works as expected
```
co.sitic.pp
com.hmdglobal.enterprise.api
com.qualcomm.qti.qms.service.telemetry
com.qualcomm.qti.qmmi
com.qualcomm.qti.qdma
```
I should also mention that `adb shell rm -r /data/dalvik-cache` gives me an error:
`rm: /data/dalvik-cache: Permission denied`
and `adb shell ls /data/`:
`ls: /data/: Permission denied`
and `adb shell ls /`:
```
ls: //cache: Permission denied
ls: //init.environ.rc: Permission denied
ls: //init.rc: Permission denied
ls: //ueventd.rc: Permission denied
ls: //init.zygote64_32.rc: Permission denied
ls: //init: Permission denied
ls: //init.usb.configfs.rc: Permission denied
ls: //pixelworks: Permission denied
ls: //init.recovery.qcom.rc: Permission denied
ls: //init.usb.rc: Permission denied
ls: //init.cdfinger.rc: Permission denied
ls: //init.zygote32.rc: Permission denied
ls: //postinstall: Permission denied
acct
bin
bugreports
charger
config
d
data
default.prop
dev
etc
lost+found
mnt
odm
oem
proc
product
res
sbin
sdcard
storage
sys
system
vendor
```

So the folder is still there, but we no longer have access to it, so I had to skip that step.

**Comment by thanuj10** [comment]
Okay i'll add the apps later tonight or tomorrow. 
Also, I just realised that `rm -rf /data/dalvik-cache` is only accessible if you have root access on your phone. Ill make changes accordingly. 

`rm -rf /data/cache` is still accessible though. 

Also if you can pass the command `list packages -s` via adb and send me the list.

**Comment by omicron-b** [comment]
Thanks!
> `rm -rf /data/cache` is still accessible though.

Not on my device
```
$ adb shell ls /data/cache
ls: /data/cache: Permission denied
$ adb shell rm -rf /data/cache
rm: chmod '/data/cache' to 0700: Permission denied
rm: No /data/cache: Permission denied
```
I also removed some Google apps, so the list below would not be full.
I removed:
```
com.google.android.apps.wellbeing
com.google.android.apps.magazines
com.google.ar.lens
com.google.android.apps.messaging
com.google.android.apps.photos
```

And here is what is left:
```
$ adb shell pm list packages -s
package:com.google.android.apps.subscriptions.red
package:com.android.cts.priv.ctsshim
package:com.gd.mobicore.pa
package:com.google.android.youtube
package:com.android.internal.display.cutout.emulation.corner
package:com.google.android.ext.services
package:com.android.internal.display.cutout.emulation.double
package:com.android.providers.telephony
package:com.hmdglobal.app.puredisplay
package:com.google.android.googlequicksearchbox
package:com.android.providers.calendar
package:com.google.android.apps.googleassistant
package:com.android.providers.media
package:com.google.android.onetimeinitializer
package:com.google.android.ext.shared
package:com.android.wallpapercropper
package:com.quicinc.cne.CNEService
package:com.android.protips
package:com.qualcomm.qti.smcinvokepkgmgr
package:com.android.documentsui
package:com.android.externalstorage
package:com.android.htmlviewer
package:com.qualcomm.qti.uceShimService
package:com.android.companiondevicemanager
package:com.hmdglobal.app.activation
package:com.android.mms.service
package:com.wos.face.service
package:com.qualcomm.qti.qms.service.connectionsecurity
package:com.android.providers.downloads
package:com.qualcomm.qtil.aptxalsOverlay
package:com.android.partnerbrowsercustomizations.example
package:com.qualcomm.qti.callenhancement
package:com.qualcomm.qti.telephonyservice
package:com.picmix.mobile
package:com.qualcomm.qti.auth.fidocryptoservice
package:com.google.android.configupdater
package:com.qualcomm.qti.optinoverlay
package:com.android.defcontainer
package:com.qti.confuridialer
package:com.android.providers.downloads.ui
package:com.android.vending
package:com.android.pacprocessor
package:com.android.simappdialog
package:com.android.settings.overlay.cmcc
package:com.android.internal.display.cutout.emulation.tall
package:com.android.certinstaller
package:com.android.carrierconfig
package:com.google.android.marvin.talkback
package:org.codeaurora.bluetooth
package:com.google.android.apps.work.oobconfig
package:com.android.mms.overlay.cmcc
package:com.qti.qualcomm.datastatusnotification
package:com.hmdglobal.app.fmradio
package:android
package:com.qualcomm.qti.callfeaturessetting
package:com.qualcomm.wfd.service
package:com.qualcomm.qtil.aptxals
package:android.ui.overlay.ct
package:com.qti.qualcomm.deviceinfo
package:com.android.egg
package:com.android.mtp
package:com.android.nfc
package:com.android.stk
package:com.android.launcher3
package:com.android.backupconfirm
package:com.google.android.deskclock
package:org.codeaurora.ims
package:com.android.statementservice
package:com.google.android.as
package:com.google.android.gm
package:com.android.settings.intelligence
package:com.android.systemui.theme.dark
package:com.qualcomm.qti.dynamicddsservice
package:com.google.android.setupwizard
package:com.qualcomm.qcrilmsgtunnel
package:com.android.providers.settings
package:com.android.sharedstoragebackup
package:com.android.printspooler
package:com.android.dreams.basic
package:com.android.se
package:com.android.inputdevices
package:com.google.android.dialer
package:com.android.bips
package:com.qti.dpmserviceapp
package:com.google.android.apps.nbu.files
package:android.autoinstalls.config.hmdglobal.starlord
package:com.qti.xdivert
package:com.android.systemui.overlay.cmcc
package:com.android.musicfx
package:com.android.settings.overlay.common
package:com.hmdglobal.app.setupwizardext
package:com.google.android.apps.docs
package:com.google.android.apps.maps
package:com.android.cellbroadcastreceiver
package:com.google.android.webview
package:android.telephony.overlay.cmcc
package:com.qualcomm.qti.simsettings
package:com.google.android.contacts
package:com.android.server.telecom
package:com.google.android.syncadapters.contacts
package:com.android.backup
package:com.android.keychain
package:com.android.chrome
package:com.google.android.packageinstaller
package:com.google.android.gms
package:com.google.android.gsf
package:com.google.android.ims
package:com.google.android.tag
package:com.google.android.tts
package:com.google.android.gmsintegration
package:com.qualcomm.qti.qtisystemservice
package:com.android.calllogbackup
package:com.google.android.partnersetup
package:com.android.carrierdefaultapp
package:com.hmdglobal.app.camera
package:com.qualcomm.qti.remoteSimlockAuth
package:com.android.proxyhandler
package:com.google.android.feedback
package:com.google.android.printservice.recommendation
package:com.google.android.calendar
package:com.android.managedprovisioning
package:com.android.providers.partnerbookmarks
package:com.android.smspush
package:com.android.networksettings.overlay.ct
package:com.trustonic.teeservice
package:com.android.wallpaper.livepicker
package:com.qualcomm.qti.seemp.service
package:com.google.android.gms.policy_sidecar_aps
package:com.google.android.backuptransport
package:com.android.storagemanager
package:com.android.bookmarkprovider
package:com.android.settings
package:com.qualcomm.qti.ims
package:com.qualcomm.qti.lpa
package:com.qualcomm.qti.uim
package:com.hmdglobal.support
package:com.qualcomm.location
package:com.qualcomm.simcontacts
package:com.google.android.apps.turbo
package:com.android.cts.ctsshim
package:com.android.systemui.overlay.ct
package:com.qualcomm.qti.services.secureui
package:com.android.vpndialogs
package:com.qualcomm.location.XT
package:com.google.android.apps.wallpaper
package:com.android.phone
package:com.android.shell
package:com.android.wallpaperbackup
package:com.android.providers.blockednumber
package:com.android.providers.userdictionary
package:com.android.emergency
package:com.qualcomm.qti.seccamservice
package:com.qualcomm.qti.roamingsettings
package:com.android.location.fused
package:com.hmdglobal.app.omacp
package:com.android.systemui
package:com.hmdglobal.app.sarauth
package:com.android.bluetoothmidiservice
package:com.qualcomm.qti.confdialer
package:com.qualcomm.qti.poweroffalarm
package:com.qualcomm.qti.networksetting
package:com.hmdglobal.app.bokeheditor
package:com.android.traceur
package:com.qualcomm.qti.qms.service.trustzoneaccess
package:com.hmdglobal.app.legalinformation
package:com.android.bluetooth
package:com.qualcomm.timeservice
package:com.android.wallpaperpicker
package:com.qualcomm.embms
package:com.android.providers.contacts
package:com.android.captiveportallogin
package:com.google.android.inputmethod.latin
package:com.google.android.apps.restore
```

**Comment by Sid127** [comment]
@omicron-b I'm the one working on the Linux version of the script, and yes, I can definitely add support to uninstall the newer apps too. Just not today, because I have an exam coming up :P

**Comment by omicron-b** [comment]
@Sid127 I know, I forked your script to quickly fix my phone :smiley: 
Thanks!

**Comment by thanuj10** [comment]
Woah okay, Thanks for the immediate response! 

There are some interesting apps and observations. I'll investigate and update 👍🏻

**Comment by thanuj10** [comment]
@omicron-b Here are my observations - 
`qualcomm apps` - No need of removing these unless you want total privacy and absolutely 0 telemetry. They should be there to send data about the processor.

`com.picmix.mobile` - This leads to a photo editing app. It seems to have been recently removed from Google Play as clicking on the search result results in a 404.

`com.hmdglobal.app.sarauth` - This leads to a gsmarena.com page where someone claims it keeps crashing on their phone. Needs more investigation which will be difficult as I do not own an end-of-2019 phone.

There isn't much bloatware aside some hmd global apps. The com.picmix.mobile app is making me curious though. Can you extract the app via Skit(Get from Google Play) and attach it here. Maybe even all the hmd apps.

**Comment by omicron-b** [comment]
> `qualcomm apps` - No need of removing these

Okay, you`re the boss

`com.picmix.mobile` - Strange, it seems disabled by vendor because I can not see it in System apps nor do I remember disabling it, yet it is disabled
![Screenshot_20200302-221042](https://user-images.githubusercontent.com/32303844/75709458-9dd6e480-5cba-11ea-8a76-dc07b1f2e903.png)
anyways, here is the [link valid for 7 days](https://send.firefox.com/download/e032b94b1f8e8313/#R_Gc4_Xr9DNSFu2U5meC_g)

`com.hmdglobal.app.sarauth` is just 36KB, in can run SarSensorService (whatever that is), can read and change phone state, vibrate, wake lock, access and change WiFi state, write system settings. I would say something useful.

`com.hmdglobal.app.omacp` can "receive WAP push messages"

`android.autoinstalls.config.hmdglobal.starlord` is dummy package with no permissions, services, resources and is something to do with PLAY_AUTO_INSTALL as per manifest, maybe it autoupdates Google Play

`com.hmdglobal.enterprise.api` i believe connects to dapi.hmdglobal.net, but i already removed it

The rest are pretty self explaining: Camera, PureDisplay, Activation (one-time telemetry), Radio, Setup Wizard, Support (lets you contact support), `com.hmdglobal.app.bokeheditor` is "Portrait Editor" (whatever that is).

I would rather not extract and post them here because the Legal text in my device specifically forbids this.

**Comment by omicron-b** [comment]
and btw here is `co.sitic.pp` (hidden 3rd party telemetry) - I saved the APK before removing it
[link valid for 7 days](https://send.firefox.com/download/1e2f2d8bcf110868/#TOYXpbskkkSSezA_5W0j7Q)

**Comment by Sid127** [comment]
`com.hmdglobal.app.sarauth` is present to authenticate the SAR data of the device - I think it should be kept.
All qualcomm apps are most likely a part of CAF.
But the picmix app is having me wondering, but I don't think any other apps need to be debloated, apart from the telemetry apps (as an option)

**Comment by Sid127** [comment]
I found something interesting
https://github.com/lucafavatella/provisioning-android

The `rm -rf /data/dalvik-cache` might not be available on your device because of an encrypted data partition.

Most apps labelled `qualcomm` or `hmdglobal` look harmless to me, but we can still debloat the teletry apps and the apps that serve no real apparent function

**Comment by omicron-b** [comment]
Indeed, I have a PIN set, so it should be encrypted

**Comment by thanuj10** [comment]
But then again most of the devices currently sold in the market are encrypted by default from the factory.

**Comment by omicron-b** [comment]
According to [Reddit user here](https://reddit.com/r/Android/comments/fde3l6/3rd_party_telemetry_found_in_nokia_smartphones/fjh4zbx?context=3), `co.sitic.pp` is a kind of killswitch from Colombian carrier

In that case, it's a bloatware that should not have been preinstalled on smartphones in all regions

**Comment by omicron-b** [comment]
[official reply from HMD](https://community.phones.nokia.com/discussion/comment/154516/#Comment_154516), also quoting here:

> We are aware of this app. We can confirm it is a customization element for an operator. For handsets that do not require this app, it will be removed during the Android 10 update, coming soon. Thanks for sharing your concerns, we can reassure you that they are unnecessary.
> 
> Best regards,
> Laura

No reply concerning the HMD telemetry, though. I will ask about that again.

**Comment by thanuj10** [comment]
@omicron-b Thanks for all the information! :)

**Comment by ghost** [comment]
> @omicron-b Thanks for all the information! :)

Are these jst disabling or completely removed ??
I use a nokia 8 with root access .
I wanted to remove this stuff totally if possible .
Pls help me out

**Comment by thanuj10** [comment]
> Are these jst disabling or completely removed ??

Disabling the processes and apps. Root access is needed to completely remove these apps.

> I use a nokia 8 with root access .

👌🏻

> I wanted to remove this stuff totally if possible

Use Terminal Debloater Module to remove these apps completely.

**Comment by ghost** [comment]
> > Are these jst disabling or completely removed ??
> 
> Disabling the processes and apps. Root access is needed to completely remove these apps.
> 
> > I use a nokia 8 with root access .
> 
> 👌🏻
> 
> > I wanted to remove this stuff totally if possible
> 
> Use Terminal Debloater Module to remove these apps completely.

But terminal debloater module doesn't show these overlays it jst shows some system apps i guess.
How can i remove them then ?? I have root pls guide me

**Comment by thanuj10** [comment]
> But terminal debloater module doesn't show these overlays it jst shows some system apps i guess.

They are located in `root/system/product/overlay`
> How can i remove them then ?? I have root pls guide me

~ Open Terminal App
~ Init Terminal Debloater 
~ Choose `Custom folder/directory/location` option
~ Follow instructions

**Comment by ghost** [comment]
> > But terminal debloater module doesn't show these overlays it jst shows some system apps i guess.
> 
> They are located in `root/system/product/overlay`
> 
> > How can i remove them then ?? I have root pls guide me
> 
> ~ Open Terminal App
> ~ Init Terminal Debloater
> ~ Choose `Custom folder/directory/location` option
> ~ Follow instructions

Will it remove all the overlays from that folder ??
Or we get a menu to slect which one ??

**Comment by ghost** [comment]
> > But terminal debloater module doesn't show these overlays it jst shows some system apps i guess.
> 
> They are located in `root/system/product/overlay`
> 
> > How can i remove them then ?? I have root pls guide me
> 
> ~ Open Terminal App
> ~ Init Terminal Debloater
> ~ Choose `Custom folder/directory/location` option
> ~ Follow instructions

Tried uninstalling one overlay  which consists of two layers the thing succeeded and rebooted to apply changes but the overlay is still present done twice but its still there

**Comment by thanuj10** [comment]
Maybe the overlays are need by the os? Idk.

**Comment by omicron-b** [comment]
For the sake of completeness of this report:
I also removed `com.qualcomm.qti.qms.service.connectionsecurity` because it started connecting to `tls.telemetry.swe.quicinc.com`, but (sorry, I can't remember where or by whom) I was told that this app scans your phone for malware. I don't need such scans though :)

**Comment by thanuj10** [comment]
`quicinc` usually makes CnE stuff for Qualcomm. It seems weird that they search for malware... Especially with telemetry in the name.
