### ISSUE TITLE
Add bg-dexopt-job after removing evenwell bloatware (Feature)

### ISSUE THREAD

**Issue by vasudev-gm** [thanuj10/Nokia-Debloater#9]
@thanuj10 
Hi, 
Thanks for the script.
I used to manually run bg-dexopt-job but I thought your script might help others who are completely used to GUI and not familiar with cmd line.

For linux with adb added to env: 

**` adb shell pm bg-dexopt-job `**

For Windows with adb added to env variables:
**` adb.exe shell pm bg-dexopt-job `**

With some echo messages as: "Optimising apps using Speed-Profile and it might take 20 mins to complete"
This script helped me eliminate bad battery life on N8.1 after March 2020 update. I've tried disabling most evenwell apps but that didn't help and nuked them and now my phone is better!

**Comment by thanuj10** [comment]
Thanks for the suggestion. But the `Dex-opt` service will start by itself when certain conditions are met. I don't think that this needs to be an absolutely must do process.

I'm just gonna make it optional, But point users towards running it whenever they debloat.

**Comment by vasudev-gm** [comment]
Yeah I understand. Nevertheless, its optional step.

After march 2020 MR release for N8.1, I don't think dex-opt is being fired whilst device is plugged in or in idle. 
Consumes more power and device heats up rather quickly.
Only after removing the bloat battery performance is back to normal and device doesn't get hot anymore. Never thought debloat could make huge difference!
You can close this issue.

**Comment by Sid127** [comment]
I'll add the command to my version (linux) of the script, thanks for the tip!

**Comment by vasudev-gm** [comment]
> I'll add the command to my version (linux) of the script, thanks for the tip!

Just notify people that it will take 10 mins or more depending on SoC. Recent phones can complete this job under 5 mins while older mid range might take 15-20 mins.

**Comment by Sid127** [comment]
yup, gotchu :)

**Comment by thanuj10** [comment]
> > I'll add the command to my version (linux) of the script, thanks for the tip!
> 
> Just notify people that it will take 10 mins or more depending on SoC. Recent phones can complete this job under 5 mins while older mid range might take 15-20 mins.

It took my 6.1 Plus around 3-5 mins with ~70 apps installed :)

Seems to make the phone fair bit smoother if im honest

**Comment by vasudev-gm** [comment]
> > > I'll add the command to my version (linux) of the script, thanks for the tip!
> > 
> > 
> > Just notify people that it will take 10 mins or more depending on SoC. Recent phones can complete this job under 5 mins while older mid range might take 15-20 mins.
> 
> It took my 6.1 Plus around 3-5 mins with ~70 apps installed :)
> 
> Seems to make the phone fair bit smoother if im honest

Its true but I felt my phone slow down a tad bit after a month or so. So I compiled all packages and ran bg dexopt. 
70 apps is too small! I've almost 320+ apps eventhough I've just installed Whatsapp, Firefox, Outlook and SD Maid.
Do you know what hmdglobal.datago overaly and app does? I removed it w/o any effects but as a side-effect I'm seeing better LTE speeds from 40Mbps to 80-90Mbps download and 10-12Mbps uploads, which is close to iPhone 7 Intel modem with 101Mbps download speed and 4Mbps upload.

**Comment by thanuj10** [comment]
> HMD Global data go

It's a telemetry app.
